[package]
name = "rsauth"
version = "0.1.0"
authors = ["Dan Skorupski <boardwalk@ersatsz.com>"]

[dependencies]
base64 = "*"
futures = "*"
hyper = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sodiumoxide = "*"