[package]
name = "rsauth_common"
version = "0.1.0"
authors = ["Dan Skorupski <boardwalk@ersatsz.com>"]
edition = "2018"

[dependencies]
base32 = "*"
regex = "*"
serde = { version = "*", features = ["derive"] }
sodiumoxide = "*"