[package]
name = "rsauth_common"
version = "0.1.0"
authors = ["Dan Skorupski <boardwalk@ersatsz.com>"]
edition = "2018"

[dependencies]
base32 = "0.4"
ipnetwork = "0.16"
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
sodiumoxide = "0.2"